Fix missing ref in GitHub actions?
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--abbrev-ref', 'testing']' returned non-zero exit status 128.